apiVersion: v1
kind: Pod
metadata:
  name: sarva-test
spec:
  containers:
   - name: maven
     image: maven:3.8.1-jdk-8
     command: ["sleep", "43200"]
   - name: kaniko
     image: gcr.io/kaniko-project/executor:debug
     command: ["sleep", "43200"]
     volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
   - name: kaniko-secret
     secret:
      secretName: dockercred
      items:
      - key: .dockerconfigjson
        path: config.json