apiVersion: v1
kind: Pod
metadata:
  name: sarva-test
spec:
  containers:
   - name: kaniko
     image: gcr.io/kaniko-project/executor:5aab7cdae26cf005ab48f4ae356e1c3e328a64a6-debug
     command: ["sleep", "1d"]
     volumeMounts:
      - name: docker-config
        mountPath: /kaniko/.docker
   - name: maven
     image: maven:3.8.1-jdk-8
     command: ["sleep", "1d"]
   
  restartPolicy: Never
  volumes:
   - name: docker-config
     configMap:
      name: docker-config