apiVersion: v1
kind: Pod
metadata:
  name: sarva-test
spec:
  containers:
   - name: kaniko
     image: gcr.io/kaniko-project/executor:v1.14.0
     command: ["sleep", "1d"]
     volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
   - name: maven
     image: maven:3.8.1-jdk-8
     command: ["sleep", "1d"]
   
  restartPolicy: Never
  volumes:
   - name: kaniko-secret
     secret:
      secretName: dockercred
      items:
      - key: .dockerconfigjson
        path: config.json